import type { BaseTranslation } from '../i18n-types'

const urls = {
  luaCompletionApi: 'https://raw.githubusercontent.com/Berserk-Games/atom-tabletopsimulator-lua/master/lib/api.json',
  versionControl: 'https://tts-vscode.rolandostar.com/guides/versionControl',
  settings: {
    fileManagement: 'https://tts-vscode.rolandostar.com/extension/configuration#file-management'
  }
}

const extLabel = 'TTS'

const enUS = {
  activation: `[${extLabel}] Activating extension`,
  TTSService: {
    XMLDefaultText: `<!--File automatically generated by VSCode, change this behaviour with "ttslua.fileManagement.createXML" setting-->\n<!--Learn more at ${urls.settings.fileManagement}-->`
  },
  workDir: {
    hover: `Click to select TTSLua working directory [[Learn More]](${urls.versionControl})`,
    createFailed: 'Failed to create temporary folder: {0:string}',
    defaultTag: 'Default',
    noGitReposInWorkspace: 'No git repositories found in workspace',
    quickPickPlaceHolder: 'Select working directory to store TTS scripts',
    failedToSelect: 'Failed to select workspace folder, please try again',
    removed: 'The currently selected working directory is not available in the workspace.\nPlease select a new one or re-add it to the workspace.\n\nDefault working directory will be added when getting scripts. (Ctrl + Alt + L)'
  },
  docs: {
    learnMore: 'Learn More'
  },
  explorer: {
    defaultWorkDirName: 'Tabletop Simulator Files'
  },
  prompts: {
    getScriptsConfirm: 'Get Lua Scripts from game?\n\n This will erase any changes that you have made since the last Save & Play.',
    getScriptsConfirmButton: 'Get Scripts'
  },
  urls,
  errors: {
    serverError: `[${extLabel}] Unexpected Server Error:`,
    gameNotRunning: 'Unable to connect to Tabletop Simulator.\n\nCheck that the game is running and a save has been loaded.',
    anotherInstanceRunning: 'Another instance of VSCode or Atom is already running',
    anotherInstanceRunningDetail: 'Please close the other instance and try again.',
    uriStatUnexpected: 'Unexpected error while checking if "{0:string}" exists: {1:string}'
  }
} satisfies BaseTranslation

export default enUS
