// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'es-MX'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * [​T​T​S​L​u​a​]​ ​A​c​t​i​v​a​t​i​n​g​ ​e​x​t​e​n​s​i​o​n
	 */
	activation: string
	workDir: {
		/**
		 * C​l​i​c​k​ ​t​o​ ​s​e​l​e​c​t​ ​T​T​S​L​u​a​ ​w​o​r​k​i​n​g​ ​d​i​r​e​c​t​o​r​y​ ​[​[​L​e​a​r​n​ ​M​o​r​e​]​]​(​h​t​t​p​s​:​/​/​t​t​s​-​v​s​c​o​d​e​.​r​o​l​a​n​d​o​s​t​a​r​.​c​o​m​/​g​u​i​d​e​s​/​v​e​r​s​i​o​n​C​o​n​t​r​o​l​)
		 */
		hover: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​t​e​m​p​o​r​a​r​y​ ​f​o​l​d​e​r​:​ ​{​0​}
		 * @param {string} 0
		 */
		createFailed: RequiredParams<'0'>
		/**
		 * D​e​f​a​u​l​t
		 */
		defaultTag: string
		/**
		 * N​o​ ​g​i​t​ ​r​e​p​o​s​i​t​o​r​i​e​s​ ​f​o​u​n​d​ ​i​n​ ​w​o​r​k​s​p​a​c​e
		 */
		noGitReposInWorkspace: string
		/**
		 * S​e​l​e​c​t​ ​w​o​r​k​i​n​g​ ​d​i​r​e​c​t​o​r​y​ ​t​o​ ​s​t​o​r​e​ ​T​T​S​ ​s​c​r​i​p​t​s
		 */
		quickPickPlaceHolder: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​s​e​l​e​c​t​ ​w​o​r​k​s​p​a​c​e​ ​f​o​l​d​e​r​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n
		 */
		failedToSelect: string
	}
	docs: {
		/**
		 * L​e​a​r​n​ ​M​o​r​e
		 */
		learnMore: string
		urls: {
			/**
			 * h​t​t​p​s​:​/​/​t​t​s​-​v​s​c​o​d​e​.​r​o​l​a​n​d​o​s​t​a​r​.​c​o​m​/​g​u​i​d​e​s​/​v​e​r​s​i​o​n​C​o​n​t​r​o​l
			 */
			versionControl: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * [TTSLua] Activating extension
	 */
	activation: () => LocalizedString
	workDir: {
		/**
		 * Click to select TTSLua working directory [[Learn More]](https://tts-vscode.rolandostar.com/guides/versionControl)
		 */
		hover: () => LocalizedString
		/**
		 * Failed to create temporary folder: {0}
		 */
		createFailed: (arg0: string) => LocalizedString
		/**
		 * Default
		 */
		defaultTag: () => LocalizedString
		/**
		 * No git repositories found in workspace
		 */
		noGitReposInWorkspace: () => LocalizedString
		/**
		 * Select working directory to store TTS scripts
		 */
		quickPickPlaceHolder: () => LocalizedString
		/**
		 * Failed to select workspace folder, please try again
		 */
		failedToSelect: () => LocalizedString
	}
	docs: {
		/**
		 * Learn More
		 */
		learnMore: () => LocalizedString
		urls: {
			/**
			 * https://tts-vscode.rolandostar.com/guides/versionControl
			 */
			versionControl: () => LocalizedString
		}
	}
}

export type Formatters = {}
