// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'es-MX'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * [​T​T​S​]​ ​A​c​t​i​v​a​t​i​n​g​ ​e​x​t​e​n​s​i​o​n
	 */
	activation: string
	TTSService: {
		/**
		 * <​!​-​-​F​i​l​e​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​g​e​n​e​r​a​t​e​d​ ​b​y​ ​V​S​C​o​d​e​,​ ​c​h​a​n​g​e​ ​t​h​i​s​ ​b​e​h​a​v​i​o​u​r​ ​w​i​t​h​ ​"​t​t​s​l​u​a​.​f​i​l​e​M​a​n​a​g​e​m​e​n​t​.​c​r​e​a​t​e​X​M​L​"​ ​s​e​t​t​i​n​g​-​-​>​
	​<​!​-​-​L​e​a​r​n​ ​m​o​r​e​ ​a​t​ ​h​t​t​p​s​:​/​/​t​t​s​-​v​s​c​o​d​e​.​r​o​l​a​n​d​o​s​t​a​r​.​c​o​m​/​e​x​t​e​n​s​i​o​n​/​c​o​n​f​i​g​u​r​a​t​i​o​n​#​f​i​l​e​-​m​a​n​a​g​e​m​e​n​t​-​-​>
		 */
		XMLDefaultText: string
	}
	workDir: {
		/**
		 * C​l​i​c​k​ ​t​o​ ​s​e​l​e​c​t​ ​T​T​S​L​u​a​ ​w​o​r​k​i​n​g​ ​d​i​r​e​c​t​o​r​y​ ​[​[​L​e​a​r​n​ ​M​o​r​e​]​]​(​h​t​t​p​s​:​/​/​t​t​s​-​v​s​c​o​d​e​.​r​o​l​a​n​d​o​s​t​a​r​.​c​o​m​/​g​u​i​d​e​s​/​v​e​r​s​i​o​n​C​o​n​t​r​o​l​)
		 */
		hover: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​t​e​m​p​o​r​a​r​y​ ​f​o​l​d​e​r​:​ ​{​0​}
		 * @param {string} 0
		 */
		createFailed: RequiredParams<'0'>
		/**
		 * T​T​S​ ​[​D​e​f​a​u​l​t​]
		 */
		defaultTag: string
		/**
		 * T​T​S​ ​[​R​e​m​o​v​e​d​]
		 */
		removedTag: string
		/**
		 * N​o​ ​g​i​t​ ​r​e​p​o​s​i​t​o​r​i​e​s​ ​f​o​u​n​d​ ​i​n​ ​w​o​r​k​s​p​a​c​e
		 */
		noGitReposInWorkspace: string
		/**
		 * S​e​l​e​c​t​ ​w​o​r​k​i​n​g​ ​d​i​r​e​c​t​o​r​y​ ​t​o​ ​s​t​o​r​e​ ​T​T​S​ ​s​c​r​i​p​t​s
		 */
		quickPickPlaceHolder: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​s​e​l​e​c​t​ ​w​o​r​k​s​p​a​c​e​ ​f​o​l​d​e​r​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n
		 */
		failedToSelect: string
		/**
		 * T​h​e​ ​c​u​r​r​e​n​t​l​y​ ​s​e​l​e​c​t​e​d​ ​w​o​r​k​i​n​g​ ​d​i​r​e​c​t​o​r​y​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​i​n​ ​t​h​e​ ​w​o​r​k​s​p​a​c​e​.​
	​P​l​e​a​s​e​ ​s​e​l​e​c​t​ ​a​ ​n​e​w​ ​o​n​e​ ​o​r​ ​r​e​-​a​d​d​ ​i​t​ ​t​o​ ​t​h​e​ ​w​o​r​k​s​p​a​c​e​.​
	​
	​D​e​f​a​u​l​t​ ​w​o​r​k​i​n​g​ ​d​i​r​e​c​t​o​r​y​ ​w​i​l​l​ ​b​e​ ​a​d​d​e​d​ ​w​h​e​n​ ​g​e​t​t​i​n​g​ ​s​c​r​i​p​t​s​.​ ​(​C​t​r​l​ ​+​ ​A​l​t​ ​+​ ​L​)
		 */
		removed: string
	}
	docs: {
		/**
		 * L​e​a​r​n​ ​M​o​r​e
		 */
		learnMore: string
	}
	explorer: {
		/**
		 * T​a​b​l​e​t​o​p​ ​S​i​m​u​l​a​t​o​r​ ​F​i​l​e​s
		 */
		defaultWorkDirName: string
	}
	TTSConsole: {
		/**
		 * T​T​S​C​o​n​s​o​l​e
		 */
		viewType: string
		/**
		 * T​a​b​l​e​t​o​p​ ​S​i​m​u​l​a​t​o​r​ ​C​o​n​s​o​l​e​+​+
		 */
		title: string
	}
	prompts: {
		/**
		 * G​e​t​ ​L​u​a​ ​S​c​r​i​p​t​s​ ​f​r​o​m​ ​g​a​m​e​?​
	​
	​T​h​i​s​ ​w​i​l​l​ ​e​r​a​s​e​ ​a​n​y​ ​c​h​a​n​g​e​s​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​m​a​d​e​ ​s​i​n​c​e​ ​t​h​e​ ​l​a​s​t​ ​S​a​v​e​ ​&​ ​P​l​a​y​.
		 */
		getScriptsCanceled: string
		/**
		 * G​e​t​ ​S​c​r​i​p​t​s
		 */
		getScriptsCanceledButton: string
		/**
		 * T​e​s​t​ ​P​r​o​m​p​t​ ​w​i​t​h​o​u​t​ ​b​u​t​t​o​n
		 */
		getScriptsTest: string
	}
	urls: {
		/**
		 * h​t​t​p​s​:​/​/​r​a​w​.​g​i​t​h​u​b​u​s​e​r​c​o​n​t​e​n​t​.​c​o​m​/​B​e​r​s​e​r​k​-​G​a​m​e​s​/​a​t​o​m​-​t​a​b​l​e​t​o​p​s​i​m​u​l​a​t​o​r​-​l​u​a​/​m​a​s​t​e​r​/​l​i​b​/​a​p​i​.​j​s​o​n
		 */
		luaCompletionApi: string
		/**
		 * h​t​t​p​s​:​/​/​t​t​s​-​v​s​c​o​d​e​.​r​o​l​a​n​d​o​s​t​a​r​.​c​o​m​/​g​u​i​d​e​s​/​v​e​r​s​i​o​n​C​o​n​t​r​o​l
		 */
		versionControl: string
		settings: {
			/**
			 * h​t​t​p​s​:​/​/​t​t​s​-​v​s​c​o​d​e​.​r​o​l​a​n​d​o​s​t​a​r​.​c​o​m​/​e​x​t​e​n​s​i​o​n​/​c​o​n​f​i​g​u​r​a​t​i​o​n​#​f​i​l​e​-​m​a​n​a​g​e​m​e​n​t
			 */
			fileManagement: string
		}
	}
	errors: {
		/**
		 * [​T​T​S​]​ ​U​n​e​x​p​e​c​t​e​d​ ​S​e​r​v​e​r​ ​E​r​r​o​r​:
		 */
		serverError: string
		/**
		 * U​n​a​b​l​e​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​o​ ​T​a​b​l​e​t​o​p​ ​S​i​m​u​l​a​t​o​r​.​
	​
	​C​h​e​c​k​ ​t​h​a​t​ ​t​h​e​ ​g​a​m​e​ ​i​s​ ​r​u​n​n​i​n​g​ ​a​n​d​ ​a​ ​s​a​v​e​ ​h​a​s​ ​b​e​e​n​ ​l​o​a​d​e​d​.
		 */
		gameNotRunning: string
		/**
		 * A​n​o​t​h​e​r​ ​i​n​s​t​a​n​c​e​ ​o​f​ ​V​S​C​o​d​e​ ​o​r​ ​A​t​o​m​ ​i​s​ ​a​l​r​e​a​d​y​ ​r​u​n​n​i​n​g
		 */
		anotherInstanceRunning: string
		/**
		 * P​l​e​a​s​e​ ​c​l​o​s​e​ ​t​h​e​ ​o​t​h​e​r​ ​i​n​s​t​a​n​c​e​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		anotherInstanceRunningDetail: string
		/**
		 * U​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​ ​w​h​i​l​e​ ​c​h​e​c​k​i​n​g​ ​i​f​ ​"​{​0​}​"​ ​e​x​i​s​t​s​:​ ​{​1​}
		 * @param {string} 0
		 * @param {string} 1
		 */
		uriStatUnexpected: RequiredParams<'0' | '1'>
	}
}

export type TranslationFunctions = {
	/**
	 * [TTS] Activating extension
	 */
	activation: () => LocalizedString
	TTSService: {
		/**
		 * <!--File automatically generated by VSCode, change this behaviour with "ttslua.fileManagement.createXML" setting-->
	<!--Learn more at https://tts-vscode.rolandostar.com/extension/configuration#file-management-->
		 */
		XMLDefaultText: () => LocalizedString
	}
	workDir: {
		/**
		 * Click to select TTSLua working directory [[Learn More]](https://tts-vscode.rolandostar.com/guides/versionControl)
		 */
		hover: () => LocalizedString
		/**
		 * Failed to create temporary folder: {0}
		 */
		createFailed: (arg0: string) => LocalizedString
		/**
		 * TTS [Default]
		 */
		defaultTag: () => LocalizedString
		/**
		 * TTS [Removed]
		 */
		removedTag: () => LocalizedString
		/**
		 * No git repositories found in workspace
		 */
		noGitReposInWorkspace: () => LocalizedString
		/**
		 * Select working directory to store TTS scripts
		 */
		quickPickPlaceHolder: () => LocalizedString
		/**
		 * Failed to select workspace folder, please try again
		 */
		failedToSelect: () => LocalizedString
		/**
		 * The currently selected working directory is not available in the workspace.
	Please select a new one or re-add it to the workspace.

	Default working directory will be added when getting scripts. (Ctrl + Alt + L)
		 */
		removed: () => LocalizedString
	}
	docs: {
		/**
		 * Learn More
		 */
		learnMore: () => LocalizedString
	}
	explorer: {
		/**
		 * Tabletop Simulator Files
		 */
		defaultWorkDirName: () => LocalizedString
	}
	TTSConsole: {
		/**
		 * TTSConsole
		 */
		viewType: () => LocalizedString
		/**
		 * Tabletop Simulator Console++
		 */
		title: () => LocalizedString
	}
	prompts: {
		/**
		 * Get Lua Scripts from game?

	This will erase any changes that you have made since the last Save & Play.
		 */
		getScriptsCanceled: () => LocalizedString
		/**
		 * Get Scripts
		 */
		getScriptsCanceledButton: () => LocalizedString
		/**
		 * Test Prompt without button
		 */
		getScriptsTest: () => LocalizedString
	}
	urls: {
		/**
		 * https://raw.githubusercontent.com/Berserk-Games/atom-tabletopsimulator-lua/master/lib/api.json
		 */
		luaCompletionApi: () => LocalizedString
		/**
		 * https://tts-vscode.rolandostar.com/guides/versionControl
		 */
		versionControl: () => LocalizedString
		settings: {
			/**
			 * https://tts-vscode.rolandostar.com/extension/configuration#file-management
			 */
			fileManagement: () => LocalizedString
		}
	}
	errors: {
		/**
		 * [TTS] Unexpected Server Error:
		 */
		serverError: () => LocalizedString
		/**
		 * Unable to connect to Tabletop Simulator.

	Check that the game is running and a save has been loaded.
		 */
		gameNotRunning: () => LocalizedString
		/**
		 * Another instance of VSCode or Atom is already running
		 */
		anotherInstanceRunning: () => LocalizedString
		/**
		 * Please close the other instance and try again.
		 */
		anotherInstanceRunningDetail: () => LocalizedString
		/**
		 * Unexpected error while checking if "{0}" exists: {1}
		 */
		uriStatUnexpected: (arg0: string, arg1: string) => LocalizedString
	}
}

export type Formatters = {}
