
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'dev'
    paths:
    - 'docs/**.md'

name: Publish Documentation
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: Install Dependencies
        run: npm install --frozen-lockfile
      - name: Build Documentation
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build

  deploy:
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
