name: Create Release on Tag Push

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'pre-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run compile

      - name: Upload VSIX to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './your-vsix-file.vsix'
          asset_name: 'your-vsix-file.vsix'
          asset_content_type: 'application/vsix'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            *Changes or descriptions can go here*
          draft: true
          prerelease: ${{ startsWith(github.ref, 'refs/tags/pre-') }}
